# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RandomActsOfKindness' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RandomActsOfKindness
	pod 'FBSDKCoreKit', '~> 4.14'
	pod 'FBSDKLoginKit', '~> 4.14'
  target 'RandomActsOfKindnessTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
